Fix Android 12 Target-SDK 31+ issues
- Fixes the following Android 12+ issue:
java.lang.IllegalArgumentException: com.app-xxx: Targeting S+
(version 31 and above) requires that one of FLAG_IMMUTABLE or
FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE
if some functionality depends on the PendingIntent being mutable,
e.g. if it needs to be used with inline replies or bubbles.
- Starting on Gradle 7 the deprecated compile method for retrieving
dependencies is no longer supported, hence it was substituted with
implementation.